config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  resources :moussaillons

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/moussaillon.rb
class Moussaillon < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/moussaillons_controller.rb
class MoussaillonsController < ApplicationController
  def index
  	@moussaillons = Moussaillon.all
  end
  
  def new
  	@moussaillon =Moussaillon.new
  end
  
  def show
  	@moussaillon = Moussaillon.find(params[:id])
  end
  
  def edit
  	@moussaillon = Moussaillon.find(params[:id])
  end
  
  def create
  	@moussaillon = Moussaillon.create(moussaillon_params)
  	if @moussaillon.save
  		redirect_to @moussaillon
  	else
  		render 'new'
  	end
  end
  
  def update
  	@moussaillon = Moussaillon.find(params[:id])
  	if @moussaillon.update(moussaillon_params)
  		redirect_to @moussaillon
  	else
  		render 'edit'
  	end
  end

  def destroy
  	@moussaillon = Moussaillon.find(params[:id])
  	@moussaillon.destroy
  	redirect_to @moussaillon
  end

  private

  def moussaillon_params
  	params.require(:moussaillon).permit(:first_name, :age, :likeness)
  	end 
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/moussaillon_helper.rb
module MoussaillonHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Accueil", root_path %></li>
        <li><%= link_to "Index des moussaillons", moussaillons_path %></li>
        <li><%= link_to "Nouveau moussaillon", new_moussaillon_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ThpMoussaillons</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </head>

  <body>
  	<%= render "layouts/header" %>
  	<br>
  	<br>
    <%= yield %>
  </body>
</html>

app/views/moussaillons/edit.html.erb
<h1>Edit Profile</h1>
 
<%= form_for @moussaillon do |moussaillon| %>

  <p><label>Nom du moussaillon</label></p>
  <%= moussaillon.text_field :first_name %>

  <p><label>Age du moussaillon</label></p>
  <%= moussaillon.text_field :age %>

  <p>Tu préfères quoi ?</p>
  <%= moussaillon.radio_button(:likeness, "kebab") %>
  <%= label(:likeness_kebab, "Je préfère les kebabs") %>
  <%= moussaillon.radio_button(:likeness, "Kefta") %>
  <%= label(:likeness_Humouss, "Je préfère les keftas") %>
</br>
  <%= link_to "Supprimer le moussaillon", @moussaillon, :method => :delete %>

  <p><%= moussaillon.submit 'Mettre à jour' %></p>
<% end %>

app/views/moussaillons/index.html.erb
<h1>Index des Moussaillons</h1>

<table class="table table-striped">
	<tr>
		<th>Moussaillon</th>
		<th> Age </th>
		<th>Equipe</th>
	</tr>

	<% @moussaillons.each do |moussaillon| %>
	<tr>
		<td><%= moussaillon.first_name %></td>
		<td><%= moussaillon.age %> </td>
		<td><%= moussaillon.likeness %> </td>
		<td><%= link_to "Voir le profil", moussaillon_path(moussaillon.id) %></td>	
		
	</tr>
	<% end %>
</table>


 

app/views/moussaillons/new.html.erb
<h1>Nouveau moussaillon</h1>
 
<%= form_for @moussaillon, url: {action: "create"}, html: {class: "nifty_form"} do |f| %>
 <h2>Quel est ton prénom ?</h2>
  <%= f.text_field :first_name %>
  <h2>Quel âge as tu ?</h2>
  <%= f.number_field :age %>
  <%= f.submit "Create" %>
<% end %>

app/views/moussaillons/show.html.erb
<h1>Bienvenue sur le profil de <%= @moussaillon.first_name %> ! </h1>
<p> <%= @moussaillon.first_name %> a <%= @moussaillon.age %> ans </p>

<p>Ce moussaillon est un grand amateur de  <%=@moussaillon.likeness %>  </p>
<%=link_to "Editer le profil", edit_moussaillon_path, class: "btn btn-lg btn-primary"%>
<%=link_to "Retour à l'index", moussaillons_path, class: "btn btn-lg btn-primary" %>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Bienvenue !</h1>
  <h3>
    Ici, tu peux retrouver les moussaillons 🎓
  </h3>
  <%= link_to "Enregistre-toi !", new_moussaillon_path, class: "btn btn-lg btn-primary" %>
</div>